### ISSUE TITLE
Feature request: Automatic export

### ISSUE THREAD

**Issue by tkjacobsen** [greggigon/my-personal-kanban#51]
For backup purposes (e.g. if browser cache is cleared), it would be awesome if the Export functionality could be triggered automatically - either periodically or upon each update.

Secondly, if the user can set the path to be automatically save to, this allows for putting the file in e.x. Dropbox.

**Comment by jasonin2d** [comment]
Agreed; this would be very useful for anyone using this product because they are not able to use a cloud-based Kanban tool at work for privacy reasons.  This is my exact use case, so I'd like to be able to have the data automatically exported to a directory of my choosing (that I know is already backed up) so that I know my personal kanban boards through this tool are always safe.

**Comment by greggigon** [comment]
Hi
I've abandoned this solution for a new one, you can find it here: https://github.com/greggigon/mpk-desktop-app.
It a different approach with a different set of technologies in use.
I hope you will find the new version equally useful. 
Greg
